// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      coffee: {
        compile: {
          expand: true,
          cwd: 'lib/coffee',
          src: ['**/*.coffee'],
          dest: 'lib/js',
          ext: '.coffee.js',
          options: {
            bare: true,
            preserve_dirs: true
          }
        }
      },
      watch: {
        html: {
          files: ['**/*.html']
        },
        coffee: {
          files: '<%= coffee.compile.src %>',
          tasks: ['coffee']
        },
        options: {
          livereload: true
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-coffee');
    grunt.loadNpmTasks('grunt-contrib-watch');
    return grunt.registerTask('default', ['coffee', 'watch']);
  };

}).call(this);
