// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      pkg: grunt.file.readJSON('package.json'),
      less: {
        compile: {
          options: {
            compress: true,
            banner: '/*! <%= pkg.name %> <%= grunt.template.today("dd-mm-yyyy") %> */\n'
          },
          files: {
            'lib/css/styles.css': 'lib/less/styles.less'
          }
        }
      },
      coffee: {
        compile: {
          expand: true,
          cwd: 'lib/coffee',
          src: ['**/*.coffee'],
          dest: 'lib/js',
          ext: '.coffee.js',
          options: {
            bare: true,
            preserve_dirs: true
          }
        }
      },
      concat: {
        options: {
          separator: ';',
          sourceMap: true
        },
        dist: {
          src: ['lib/js/*.coffee.js'],
          dest: 'lib/js/build.js'
        }
      },
      uglify: {
        options: {
          banner: '/*! <%= pkg.name %> <%= grunt.template.today("dd-mm-yyyy") %> */\n',
          sourceMap: true
        },
        dist: {
          files: {
            'lib/js/build.min.js': ['<%= concat.dist.dest %>']
          }
        }
      },
      watch: {
        coffee: {
          files: '<%= coffee.compile.src %>',
          tasks: ['coffee', 'concat', 'uglify']
        },
        less: {
          files: ['lib/less/styles.less'],
          tasks: ['less']
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-coffee');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-concat');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-less');
    return grunt.registerTask('default', ['coffee', 'concat', 'uglify', 'less', 'watch']);
  };

}).call(this);
